# Generated by Django 5.0.4 on 2024-04-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("summary", models.CharField(max_length=100, null=True)),
                ("content", models.TextField()),
                ("price", models.IntegerField()),
                ("img_url", models.URLField(null=True)),
                ("img_dir", models.ImageField(null=True, upload_to="product_images/")),
                ("detail_category", models.ManyToManyField(to="products.categories")),
            ],
        ),
    ]
