# Generated by Django 5.0.4 on 2024-04-22 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_products_img_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="img_dir",
        ),
    ]
