# Generated by Django 5.0.4 on 2024-04-23 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_category_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="categories",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
