# Generated by Django 4.2.11 on 2024-04-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0002_diagnosis_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="image_name",
            field=models.TextField(default="sample"),
            preserve_default=False,
        ),
    ]
