# Generated by Django 4.2.11 on 2024-04-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0003_diagnosis_image_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="image_name",
            field=models.TextField(null=True),
        ),
    ]
