# Generated by Django 5.0.4 on 2024-04-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mypage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="img_url",
            field=models.TextField(null=True),
        ),
    ]
