# Generated by Django 5.0.4 on 2024-04-25 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_dog_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='img_url',
        ),
    ]
